api_payout:
    resource: "@ApiPayoutBundle/Controller/"
    type:     annotation
    prefix:   /

# acme_blog:
#     resource: "@AcmeBlogBundle/Controller/"
#     type:     annotation
#     prefix:   /

payout:
    type: rest
    resource: Api\PayoutBundle\Controller\PayoutController


# pages:
#     type: rest
#     resource: Acme\BlogBundle\Controller\PageController







