_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# Backend Bundle Route
_backend:
    resource: "@BackendBundle/Resources/config/routing.yml"

api_bundle:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"

# Transactions Route
_transaction:
    type: rest
    resource: ApiBundle\Controller\PayoutController
    prefix: transactions
