BackendBundle\Entity\NotificationRequest:
    type: entity
    table: notification_request
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY

    fields:
        reciever:
            type: string
            nullable: true
            length: 155
            fixed: false
            comment: 'Notification receiver'
            column: receiver
        payload:
            type: text
            nullable: true
            comment: 'Notification payload'
            column: payload
        transactionCode:
            type: string
            nullable: true
            length: 55
            fixed: false
            comment: 'Transaction code'
            column: transaction_code
        notificationStatus:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: 'Status of the notification'
            column: notification_status
        notificationAction:
            type: string
            nullable: true
            length: 25
            fixed: false
            comment: 'Action of the notification'
            column: notification_action
        lastResponse:
            type: text
            nullable: true
            comment: 'Last notification response.'
            column: last_response
        
        createdAt:
            type: datetime
            nullable: false
            column: created_at
            gedmo:
                timestampable:
                    on: create
    lifecycleCallbacks: {  }
