parameters:
    abstract_notifier.class: BackendBundle\Library\Notification\AbstractNotifier
    transaction.notifier.tb.class: BackendBundle\Library\Notification\Notifier\TbNotifier
    notifier.class: BackendBundle\Library\Notification\Notifier

services:
    transaction.notifier:
        class: %notifier.class%
        arguments: [@doctrine.orm.entity_manager, @service_container]

    abstract_notifier:
        class: %abstract_notifier.class%
        abstrct: true
        calls:
            - [setDoctrine, [@doctrine.orm.entity_manager]]
            - [setLogger, [@logger]]

    transaction.notifier.tb:
        class: %transaction.notifier.tb.class%
        parent: abstract_notifier
