_welcome:
    path:     /
    defaults: { _controller: BackendBundle:Welcome:index }

_demo_secured:
    resource: "@BackendBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@BackendBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
