_welcome:
    path:     /
#    defaults: { _controller: BackendBundle:Welcome:index }
    defaults: { _controller: BackendBundle:Secured:login }

# backend_test:
#     resource: @BackendBundle/Controller/TestController.php
#     type: annotation
#     prefix: /test

_demo_secured:
    resource: "@BackendBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@BackendBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo