services:
    abstarct_queue_worker:
        class: BackendBundle\Library\Queue\AbstractQueueWorker
        abstrct: true
        calls:
            - [setDoctrine, [@doctrine.orm.entity_manager]]
            - [setLogger, [@logger]]

    cdex_queue_worker_factory:
        class: BackendBundle\Library\Queue\QueueWorkerFactory
        arguments: [@service_container]
        lazy: true

    cdex_queue_manager:
        class: BackendBundle\Library\Queue\QueueManager
        arguments: [@doctrine.orm.entity_manager, @logger, @cdex_queue_worker_factory]

    cdex_queue_worker.intrermex:
        class: BackendBundle\Library\Queue\Worker\IntermexWorker
        parent: abstarct_queue_worker
        calls:
            - [setSerializer, [@serializer]]

    cdex_queue_worker.bdo:
            class: BackendBundle\Library\Queue\Worker\BdoWorker
            parent: abstarct_queue_worker

    cdex_queue_worker.transnetwork:
              class: BackendBundle\Library\Queue\Worker\TransNetworkWorker
              parent: abstarct_queue_worker

    cdex_queue_worker.sanmartin:
              class: BackendBundle\Library\Queue\Worker\SanMartinWorker
              parent: abstarct_queue_worker  
              arguments: [@service_container]
              lazy: true
              
    twig.extension.backend:
        class: BackendBundle\Twig\Extension\BackendExtension
        public: false
        arguments: [@twig.loader]
        tags:
            - {name: twig.extension}

    backend.listener:
         class: BackendBundle\EventListener\ControllerListener
         arguments: [@twig.extension.backend]
         tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

imports:
    - {resource: notification_services.yml}
